server:
    servlet-path: /api
    port: 1080
spring:
  devtools:
    add-properties: true
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://mysqldb:3306/sistema?useSSL=false
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysqldb:3306/sistema?useSSL=false
    user: root
    password: root
  security:
    jwt:
      expiracao: 60
      chave-assinatura: YSBsZW1icmUgw6kgYnJhbmNh
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
      path: /h2-console
