server:
  servlet-path: /api
  port: 1080
spring:
  profiles:
    active: dev
  devtools:
    add-properties: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/sistema?useSSL=false
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/sistema?useSSL=false
    user: root
    password: root
  security:
    jwt:
      expiration: 60
      key: YSBsZW1icmUgw6kgYnJhbmNh
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
      path: /h2-console
